### ISSUE TITLE
how can use this package as infinite  number spinner

### ISSUE THREAD

**Issue by kssoftware93** [hlerenow/react-native-select-picker#2]
hi 
i want use this package  as infinite  number spinner (loop/repetitious) like datepickerAndriod like this 
[http://voidcanvas.com/wp-content/uploads/2018/01/react-native-datepicker.png](url)

**Comment by hlerenow** [comment]
Sorry, this package not support  infinite number spinner. Initially, this package is only to provide a cross-platform date selection component to ensure that the behavior of both ends is always, and the function of infinite scrolling is more difficult to implement with RN. But you can try it.Good Luck
